# Generated by Django 5.1.1 on 2025-01-11 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userhobby',
            unique_together=set(),
        ),
    ]
